---
# https://github.com/jmutai/tomcat-ansible/blob/master/tomcat-setup.yml
- name: Run Jenkins as servlet in Tomcat
  become: true
  hosts: all
  vars:
    tomcat_ver: 9.0.45
    ui_manager_user: manager           # User who can access the UI manager section only
    ui_manager_pass: Zaq!2wsxCde34rf   # UI manager user password
    ui_admin_username: admin           # User who can access bpth manager and admin UI sections
    ui_admin_pass: Zaq!2wsxCde34rf     # UI admin password
    jenkins_user: jenadm
    jenkins_pass: Zaq!2wsxCde34rfv
    jenkins_fullname: Jenkins Admin
    jenkins_email: jenadm@rhel79

  roles:
    - tomcat_jenkins
...
