---
JAVA_HOME: /usr/lib/jvm/jre
# tomcat_home: /usr/share/tomcat
tomcat_home: /opt/tomcat
tomcat_archive_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_ver }}/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
tomcat_archive_dest: /tmp/apache-tomcat-{{ tomcat_ver }}.tar.gz
jenkins_home: /opt/jenkins_home
jenkins_url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
jenkins_dest: /tmp/jenkins.war
srvs:
  - firewalld
  - tomcat

frw:
  - http
  - https
...
